services:
  - type: web
    name: donghuaworld-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /
